[package]
name = "pipeviewer"
version = "0.1.0"
authors = ["SHA888 <kresnasucandra@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.22"
crossbeam = "0.8.2"
